// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ssm_parameters
NumericVector ssm_parameters(NumericVector scores, NumericVector angles);
RcppExport SEXP _ssm_ssm_parameters(SEXP scoresSEXP, SEXP anglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type angles(anglesSEXP);
    rcpp_result_gen = Rcpp::wrap(ssm_parameters(scores, angles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ssm_ssm_parameters", (DL_FUNC) &_ssm_ssm_parameters, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ssm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
