#' Standardized octant scores on hypothetical circumplex scales
#'
#' A small example dataset containing standardized scores on eight hypothetical
#' circumplex scales. Taken from Wright, Pincus, Conroy, & Hilsenroth (2009).
#'
#' @format A data frame with 5 observations and 8 variables:
#' \describe{
#'   \item{PA}{circumplex scale at 90 degrees}
#'   \item{BC}{circumplex scale at 135 degrees}
#'   \item{DE}{circumplex scale at 180 degrees}
#'   \item{FG}{circumplex scale at 225 degrees}
#'   \item{HI}{circumplex scale at 270 degrees}
#'   \item{JK}{circumplex scale at 315 degrees}
#'   \item{LM}{circumplex scale at 360 degrees}
#'   \item{NO}{circumplex scale at 45 degrees}
#' }
#' @source \doi{10.1080/00223890902935696}
"aw2009"

#' Raw octant scores on real circumplex scales with covariates
#'
#' A large example dataset containing gender, raw mean scores on the Inventory
#' of Interpersonal Problems - Short Circumplex (IIP-SC), and raw sum scores on
#' the Personality Diagnostic Questionnaire - 4th Edition Plus (PDQ-4+).
#'
#' @format A data frame with 1166 observations and 19 variables:
#' \describe{
#'   \item{Gender}{Self-reported Gender}
#'   \item{PA}{Domineering Problems (IIP-SC) 90 degrees}
#'   \item{BC}{Vindictive Problems (IIP-SC) 135 degrees}
#'   \item{DE}{Cold Problems (IIP-SC) 180 degrees}
#'   \item{FG}{Socially Avoidant Problems (IIP-SC) 225 degrees}
#'   \item{HI}{Nonassertive Problems(IIP-SC) 270 degrees}
#'   \item{JK}{Easily Exploited Problems (IIP-SC) 315 degrees}
#'   \item{LM}{Overly Nurturant Problems (IIP-SC) 360 degrees}
#'   \item{NO}{Intrusive Problems (IIP-SC) 45 degrees}
#'   \item{PARPD}{Paranoid PD Symptoms (PDQ-4+)}
#'   \item{SCZPD}{Schizoid PD Symptoms (PDQ-4+)}
#'   \item{SZTPD}{Schizotypal PD Symptoms (PDQ-4+)}
#'   \item{ASPD}{Antisocial PD Symptoms (PDQ-4+)}
#'   \item{BORPD}{Borderline PD Symptoms (PDQ-4+)}
#'   \item{HISPD}{Histrionic PD Symptoms (PDQ-4+)}
#'   \item{NARPD}{Narcissistic PD Symptoms (PDQ-4+)}
#'   \item{AVPD}{Avoidant PD Symptoms (PDQ-4+)}
#'   \item{DPNPD}{Dependent PD Symptoms (PDQ-4+)}
#'   \item{OCPD}{Obsessive-Compulsive PD Symptoms (PDQ-4+)}
#' }
#' @source \doi{10.1177/1073191115621795}
"jz2017"

#' Raw item responses on real circumplex scales
#'
#' A small example dataset containing raw item responses on the Inventory of
#' Interpersonal Problems, Short Circumplex (IIP-SC). This data set is useful
#' for testing functions that operate on item-level data.
#'
#' @format A data frame with 10 observations and 32 variables.
"raw_iipsc"

#' Simulated item responses on octant circumplex scales
#'
#' A simulated item-level dataset for demonstrating [axes_reliability()]. It
#' contains 1-7 Likert responses from 500 respondents on 32 items -- four items
#' on each of the eight octant circumplex scales (`PA` at 90 degrees through
#' `NO` at 45 degrees, following [octants()]). The items were drawn from the
#' five-component population of Strack, Jacobs, and Grosse Holtforth (2013): a
#' general factor, two equal circumplex axes (axes variance .18), one shared
#' scale-specificity component (.10), no block specificity (the instrument is
#' not blockwise, so that fifth component is zero here), and free item error,
#' giving an axes reliability of about .78. The data are synthetic -- there is no public
#' raw-data source for the method -- and are generated by a seeded script
#' (`data-raw/simulated_items.R`).
#'
#' @format A data frame with 500 observations and 32 variables named
#'   `PA_1`--`PA_4`, `BC_1`--`BC_4`, ..., `NO_1`--`NO_4` (four items per octant
#'   scale).
#' @references Strack, S., Jacobs, K. A., & Grosse Holtforth, M. (2013). The
#'   reliability of circumplex axes. \emph{SAGE Open}, 3(2).
#'   \doi{10.1177/2158244013486115}
"simulated_items"

#' Simulated octant scores at three occasions
#'
#' A simulated dataset for demonstrating [ssm_analyze_long()] and
#' [ssm_plot_trajectory()]. The data are simulated, not collected from people.
#' 200 persons have scores on the eight octant scales at three waves. At each
#' wave the group profile is a cosine curve with elevation 0 and amplitude 0.6.
#' Its displacement
#' is 330 degrees at `T1`, 355 degrees at `T2` and 20 degrees at `T3`, so the
#' profile crosses the 0/360 degree boundary between `T2` and `T3`. Each person
#' has one offset, added to all eight scales at every wave, drawn from a normal
#' distribution with standard deviation 0.5. Each score also has its own noise,
#' drawn from a normal distribution with standard deviation 0.5.
#'
#' The data are written by a seeded script, `data-raw/simulated_occasions.R`,
#' which is not in the installed package. Read it on GitHub:
#' <https://github.com/jmgirard/circumplex/blob/master/data-raw/simulated_occasions.R>.
#'
#' @format A data frame with 600 rows (one per person per wave) and 10 columns:
#' \describe{
#'   \item{id}{Person identifier, 1 to 200.}
#'   \item{wave}{Occasion, a factor with levels `T1`, `T2` and `T3` in that
#'     order.}
#'   \item{PA, BC, DE, FG, HI, JK, LM, NO}{Scores on the eight octant scales,
#'     at the angles given by [octants()].}
#' }
"simulated_occasions"

#' Simulated octant scores for growth models
#'
#' Two simulated datasets for demonstrating growth models on SSM parameters with
#' [ssm_growth_data()], [ssm_growth_formula()] and [ssm_trajectory()]. The data
#' are simulated, not collected from people. In both datasets, 150 persons have
#' scores on the eight octant scales at waves 0 to 4.
#'
#' A person's score on a scale at a wave is the elevation 0.5, plus a person
#' elevation effect, plus
#' \eqn{(x + v_x)\cos\theta + (y + v_y)\sin\theta}{(x + v_x) cos(theta) + (y + v_y) sin(theta)},
#' plus noise. Here \eqn{\theta}{theta} is the scale angle and \eqn{(x, y)} is the group
#' coordinate at that wave. The person elevation effect has standard deviation
#' 0.30, the person effects \eqn{v_x} and \eqn{v_y} have standard deviation 0.15,
#' and the noise has standard deviation 0.40. All of them are drawn from normal
#' distributions. The person effects stay the same at every wave, and the two
#' datasets share them, so each person has the same effects in both.
#'
#' The two datasets differ in the group coordinates:
#' * In `simulated_growth`, \eqn{(x, y)} moves in a straight line, in equal steps,
#'   from the point with amplitude 0.6 at 350 degrees to the point with amplitude
#'   0.6 at 10 degrees. The displacement crosses the 0/360 degree boundary.
#' * In `simulated_growth_origin`, \eqn{x} moves in equal steps from 0.5 to -0.5,
#'   and \eqn{y} stays at 0.02. The group passes near the origin at wave 2.
#'
#' Both datasets are written by one seeded script, `data-raw/simulated_growth.R`,
#' which is not in the installed package. Read it on GitHub:
#' <https://github.com/jmgirard/circumplex/blob/master/data-raw/simulated_growth.R>.
#'
#' @format Each is a data frame with 750 rows (one per person per wave) and 10
#'   columns:
#' \describe{
#'   \item{person}{Person identifier, 1 to 150.}
#'   \item{wave}{Wave number, an integer from 0 to 4.}
#'   \item{PA, BC, DE, FG, HI, JK, LM, NO}{Scores on the eight octant scales,
#'     at the angles given by [octants()].}
#' }
#' @seealso `vignette("growth-ssm-analysis")`, which fits a growth model to
#'   both datasets.
"simulated_growth"

#' @rdname simulated_growth
"simulated_growth_origin"
