#' Standardized octant scores on hypothetical circumplex scales
#'
#' A small example dataset containing standardized scores on eight hypothetical
#' circumplex scales. Taken from Wright, Pincus, Conroy, & Hilsenroth (2009).
#'
#' @format A data frame with 5 observations and 8 variables:
#' \describe{
#'   \item{PA}{circumplex scale at 90 degrees}
#'   \item{BC}{circumplex scale at 135 degrees}
#'   \item{DE}{circumplex scale at 180 degrees}
#'   \item{FG}{circumplex scale at 225 degrees}
#'   \item{HI}{circumplex scale at 270 degrees}
#'   \item{JK}{circumplex scale at 315 degrees}
#'   \item{LM}{circumplex scale at 360 degrees}
#'   \item{NO}{circumplex scale at 45 degrees}
#' }
#' @source \doi{10.1080/00223890902935696}
"aw2009"

#' Raw octant scores on real circumplex scales with covariates
#'
#' A large example dataset containing gender, raw mean scores on the Inventory
#' of Interpersonal Problems - Short Circumplex (IIP-SC), and raw sum scores on
#' the Personality Diagnostic Questionnaire - 4th Edition Plus (PDQ-4+).
#'
#' @format A data frame with 1166 observations and 19 variables:
#' \describe{
#'   \item{Gender}{Self-reported Gender}
#'   \item{PA}{Domineering Problems (IIP-SC) 90 degrees}
#'   \item{BC}{Vindictive Problems (IIP-SC) 135 degrees}
#'   \item{DE}{Cold Problems (IIP-SC) 180 degrees}
#'   \item{FG}{Socially Avoidant Problems (IIP-SC) 225 degrees}
#'   \item{HI}{Nonassertive Problems(IIP-SC) 270 degrees}
#'   \item{JK}{Easily Exploited Problems (IIP-SC) 315 degrees}
#'   \item{LM}{Overly Nurturant Problems (IIP-SC) 360 degrees}
#'   \item{NO}{Intrusive Problems (IIP-SC) 45 degrees}
#'   \item{PARPD}{Paranoid PD Symptoms (PDQ-4+)}
#'   \item{SCZPD}{Schizoid PD Symptoms (PDQ-4+)}
#'   \item{SZTPD}{Schizotypal PD Symptoms (PDQ-4+)}
#'   \item{ASPD}{Antisocial PD Symptoms (PDQ-4+)}
#'   \item{BORPD}{Borderline PD Symptoms (PDQ-4+)}
#'   \item{HISPD}{Histrionic PD Symptoms (PDQ-4+)}
#'   \item{NARPD}{Narcissistic PD Symptoms (PDQ-4+)}
#'   \item{AVPD}{Avoidant PD Symptoms (PDQ-4+)}
#'   \item{DPNPD}{Dependent PD Symptoms (PDQ-4+)}
#'   \item{OCPD}{Obsessive-Compulsive PD Symptoms (PDQ-4+)}
#' }
#' @source \doi{10.1177/1073191115621795}
"jz2017"

#' Raw item responses on real circumplex scales
#'
#' A small example dataset containing raw item responses on the Inventory of
#' Interpersonal Problems, Short Circumplex (IIP-SC). This data set is useful
#' for testing functions that operate on item-level data.
#'
#' @format A data frame with 10 observations and 32 variables.
"raw_iipsc"

#' Simulated item responses on octant circumplex scales
#'
#' A simulated item-level dataset for demonstrating [axes_reliability()]. It
#' contains 1-7 Likert responses from 500 respondents on 32 items -- four items
#' on each of the eight octant circumplex scales (`PA` at 90 degrees through
#' `NO` at 45 degrees, following [octants()]). The items were drawn from the
#' five-component population of Strack, Jacobs, and Grosse Holtforth (2013): a
#' general factor, two equal circumplex axes (axes variance .18), one shared
#' scale-specificity component (.10), no block specificity (the instrument is
#' not blockwise, so that fifth component is zero here), and free item error,
#' giving an axes reliability of about .78. The data are synthetic -- there is no public
#' raw-data source for the method -- and are generated by a seeded script
#' (`data-raw/simulated_items.R`).
#'
#' @format A data frame with 500 observations and 32 variables named
#'   `PA_1`--`PA_4`, `BC_1`--`BC_4`, ..., `NO_1`--`NO_4` (four items per octant
#'   scale).
#' @references Strack, S., Jacobs, K. A., & Grosse Holtforth, M. (2013). The
#'   reliability of circumplex axes. \emph{SAGE Open}, 3(2).
#'   \doi{10.1177/2158244013486115}
"simulated_items"
