# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

angle_mean <- function(x) {
    .Call(`_circumplex_angle_mean`, x)
}

angle_median <- function(x) {
    .Call(`_circumplex_angle_median`, x)
}

compare_pi <- function(x) {
    .Call(`_circumplex_compare_pi`, x)
}

ssm_parameters <- function(scores, angles) {
    .Call(`_circumplex_ssm_parameters`, scores, angles)
}

group_parameters <- function(scores, angles) {
    .Call(`_circumplex_group_parameters`, scores, angles)
}

mean_scores <- function(cs, grp, lwd) {
    .Call(`_circumplex_mean_scores`, cs, grp, lwd)
}

corr_scores <- function(cs, mv, grp, lwd) {
    .Call(`_circumplex_corr_scores`, cs, mv, grp, lwd)
}

