# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

angle_mean <- function(x) {
    .Call('_circumplex_angle_mean', PACKAGE = 'circumplex', x)
}

angle_dev <- function(theta, xv) {
    .Call('_circumplex_angle_dev', PACKAGE = 'circumplex', theta, xv)
}

angle_median <- function(x) {
    .Call('_circumplex_angle_median', PACKAGE = 'circumplex', x)
}

compare_pi <- function(x) {
    .Call('_circumplex_compare_pi', PACKAGE = 'circumplex', x)
}

ssm_parameters_cpp <- function(scores, angles) {
    .Call('_circumplex_ssm_parameters_cpp', PACKAGE = 'circumplex', scores, angles)
}

group_parameters <- function(scores, angles) {
    .Call('_circumplex_group_parameters', PACKAGE = 'circumplex', scores, angles)
}

col_means <- function(x) {
    .Call('_circumplex_col_means', PACKAGE = 'circumplex', x)
}

mean_scores <- function(cs, grp, lwd) {
    .Call('_circumplex_mean_scores', PACKAGE = 'circumplex', cs, grp, lwd)
}

pairwise_r <- function(x, y) {
    .Call('_circumplex_pairwise_r', PACKAGE = 'circumplex', x, y)
}

corr_scores <- function(cs, mv, grp, lwd) {
    .Call('_circumplex_corr_scores', PACKAGE = 'circumplex', cs, mv, grp, lwd)
}

