# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate structural summary parameters
#'
#' @param scores A numeric vector of scores on multiple circumplex scales: can
#'   be either mean scores or correlations.
#' @param angles A numeric vector containing an angular displacement for each
#'   circumplex scale provided in \code{scores} (in degrees).
#' @return A numerical vector containing structural summary method parameters
#'   that describe \code{scores} given \code{angles}. The vector will contain
#'   the following values: elevation, x-axis value, y-axis value, amplitude,
#'   angular displacement (in degrees), and model fit (R-squared).
#' @export
ssm_parameters <- function(scores, angles) {
    .Call(`_ssm_ssm_parameters`, scores, angles)
}

