# SEM-based SSM (M5): latent-variable estimation + circular-aware CIs (T3).
#
# Estimates the latent (disattenuated) SSM profile of one or more external
# measures from a fitted fixed-theoretical-angle lavaan measurement model, and
# constructs confidence intervals by the draws-through-the-transform route:
# draws of the model's free parameters map to draws of the latent profile,
# which push through the OLS transform and the package's existing
# ssm_replicate_intervals() + circular-quantile machinery unchanged. No new
# interval-assembly code lives here (spec devel/m5-sem-design.md section 5.1);
# section references below trace to that spec.
#
# What is never delegated to lavaan (spec section 2.2): delta-method or
# percentile intervals for amplitude/displacement (the atan2 branch problem).
# lavaan supplies estimates and a covariance (or bootstrap replicates) of its
# free parameters -- nothing else.

# Structure extraction (spec section 4.1 / 7.2) ---------------------------------

# Locate one parameter-table row by (lhs, op, rhs), tolerating either
# orientation for symmetric (~~) rows. Returns the row index or 0 if absent.
sem_pt_row <- function(pt, lhs, op, rhs) {
  hit <- which(pt$lhs == lhs & pt$op == op & pt$rhs == rhs)
  if (length(hit) == 0 && op == "~~") {
    hit <- which(pt$lhs == rhs & pt$op == op & pt$rhs == lhs)
  }
  if (length(hit) == 0) 0L else hit[[1]]
}

# From a fitted lavaan model's parameter table, build the index/value maps the
# estimand map consumes: for every needed parameter, its free-parameter index
# (0 = fixed) and its fixed value. Compatibility is checked structurally --
# the named parameters must be present -- not by provenance (spec section 7.2),
# so fits of user-modified syntax (the partial-invariance escape hatch) work.
sem_structure <- function(fit, scales, measures) {
  pt <- lavaan::parameterTable(fit)
  p <- length(scales)
  m <- length(measures)
  factors <- c("g", "cx", "cy")

  need <- function(lhs, op, rhs) {
    i <- sem_pt_row(pt, lhs, op, rhs)
    if (i == 0L) {
      stop(
        "The lavaan fit is not structurally compatible with a fixed-angle ",
        "circumplex SSM measurement model: parameter `", lhs, " ", op, " ",
        rhs, "` is absent. Fit a model generated by ssm_sem_syntax() (or one ",
        "preserving its parameter structure).",
        call. = FALSE
      )
    }
    i
  }

  lam_row <- matrix(0L, p, 3)
  for (i in seq_len(p)) {
    for (j in seq_len(3)) {
      lam_row[i, j] <- need(factors[[j]], "=~", scales[[i]])
    }
  }
  phi_row <- matrix(0L, 3, 3)
  for (j in seq_len(3)) {
    for (k in j:3) {
      phi_row[j, k] <- phi_row[k, j] <- need(factors[[j]], "~~", factors[[k]])
    }
  }
  sm_row <- matrix(0L, 3, m)
  vm_row <- integer(m)
  for (k in seq_len(m)) {
    for (j in seq_len(3)) {
      sm_row[j, k] <- need(measures[[k]], "~~", factors[[j]])
    }
    vm_row[[k]] <- need(measures[[k]], "~~", measures[[k]])
  }

  shape <- function(rows, nr) {
    list(
      idx = matrix(pt$free[rows], nr),
      val = matrix(pt$est[rows], nr)
    )
  }

  # Tier is structural: any free loading = scaled, all fixed = strict
  tier <- if (any(pt$free[lam_row] > 0)) "scaled" else "strict"

  # Refuse the known-unidentified configuration: free loadings WITH free
  # g-plane covariances is locally unidentified exactly at phi_g = 0 (the
  # a_i <-> phi_g trade documented in devel/m5-sem-design.md section 3.1), so
  # a user-modified fit that frees them must not be summarized -- its MVN
  # draws run down the flat ridge into garbage.
  if (tier == "scaled" &&
    any(pt$free[c(phi_row[1, 2], phi_row[1, 3])] > 0)) {
    stop(
      "This fit frees the general-plane covariance(s) (g ~~ cx / g ~~ cy) ",
      "alongside free loadings; that model is locally unidentified at zero ",
      "covariance and cannot be summarized. To model a general factor ",
      "leaning into the plane, use the \"strict\" tier (fixed loadings, ",
      "free factor covariance matrix).",
      call. = FALSE
    )
  }

  list(
    lambda = shape(lam_row, p),
    phi = shape(phi_row, 3),
    sm = shape(sm_row, 3),
    vm = shape(vm_row, 1),
    npar = max(pt$free),
    tier = tier
  )
}

# Evaluate one structure component over a draws matrix (boots x npar): free
# parameters take their drawn column, fixed parameters their constant value.
# Returns a boots x length(idx) matrix in the component's column-major order.
sem_component <- function(comp, draws) {
  n <- nrow(draws)
  idx <- as.integer(comp$idx)
  val <- as.numeric(comp$val)
  out <- matrix(rep(val, each = n), n, length(val))
  free <- which(idx > 0L)
  if (length(free) > 0) out[, free] <- draws[, idx[free], drop = FALSE]
  out
}

# The estimand map (spec section 4.1): psi -> latent profile rho*. For each
# draw, scale i's common part t_i has Var(t_i) = lambda_i' Phi lambda_i and
# Cov(M_k, t_i) = lambda_i' sigma_Mk; every ingredient (including Var(M),
# model-implied) is evaluated from the drawn parameter vector, so the draws
# propagate standardization uncertainty (the section 4.4 trap). Returns, over
# a boots x npar draws matrix: rho (list per measure of boots x p), var_t
# (boots x p), and v_m (boots x m).
sem_profiles <- function(draws, struct) {
  n <- nrow(draws)
  lam <- sem_component(struct$lambda, draws) # n x 3p (col-major: g, cx, cy blocks)
  phi <- sem_component(struct$phi, draws) # n x 9
  sm <- sem_component(struct$sm, draws) # n x 3m
  vm <- sem_component(struct$vm, draws) # n x m
  p <- ncol(lam) / 3
  m <- ncol(vm)

  lg <- lam[, seq_len(p), drop = FALSE]
  lx <- lam[, p + seq_len(p), drop = FALSE]
  ly <- lam[, 2 * p + seq_len(p), drop = FALSE]
  # Phi entries as draw vectors (symmetric; column-major 3x3)
  f_gg <- phi[, 1]
  f_gx <- phi[, 2]
  f_gy <- phi[, 3]
  f_xx <- phi[, 5]
  f_xy <- phi[, 6]
  f_yy <- phi[, 9]

  # Var(t_i) = lambda_i' Phi lambda_i, vectorized over draws (a boots-length
  # vector recycles down each column of a boots x p matrix)
  var_t <- lg^2 * f_gg + lx^2 * f_xx + ly^2 * f_yy +
    2 * (lg * lx * f_gx + lg * ly * f_gy + lx * ly * f_xy)

  rho <- vector("list", m)
  for (k in seq_len(m)) {
    s_g <- sm[, 3 * (k - 1) + 1]
    s_x <- sm[, 3 * (k - 1) + 2]
    s_y <- sm[, 3 * (k - 1) + 3]
    cov_mt <- lg * s_g + lx * s_x + ly * s_y
    # A nonpositive variance product makes the draw inadmissible (section 4.5);
    # mask it to NA here so no sqrt warning fires -- the engine-side filter
    # downstream drops and reports these draws by cause.
    den <- var_t * vm[, k]
    den[den <= 0] <- NA_real_
    rho[[k]] <- cov_mt / sqrt(den)
  }
  list(rho = rho, var_t = var_t, v_m = vm)
}

# The SSM transform (spec section 2) ---------------------------------------------

# OLS profile -> (e, x, y, a, d, fit) in ssm_param_names() order, d in radians
# in [0, 2*pi). The linear stage is the section 2.1 projection W (equal to the
# closed form at equally spaced angles; genuinely different off harmonic
# balance, where this -- not ssm_parameters_cpp()'s closed form -- is the
# latent estimand's functional). Degenerate-NA semantics mirror
# src/parameters.cpp at the same machine-noise tolerance: flat profile ->
# displacement and fit NA; zero first-harmonic amplitude with real variance ->
# displacement NA, fit exactly 0. Under OLS the fit is a genuine bounded
# R-squared in [0, 1] at any spacing.
sem_ssm_transform <- function(profile, weights, angles_rad) {
  exy <- as.numeric(weights %*% profile)
  e <- exy[[1]]
  x <- exy[[2]]
  y <- exy[[3]]
  a <- sqrt(x^2 + y^2)
  n <- length(profile)
  tol <- 8 * .Machine$double.eps * n * max(abs(profile))
  if (!(stats::sd(profile) > tol)) {
    d <- NA_real_
    fit <- NA_real_
  } else if (a <= tol) {
    d <- NA_real_
    fit <- 0
  } else {
    d <- atan2(y, x) %% (2 * pi)
    pred <- e + x * cos(angles_rad) + y * sin(angles_rad)
    fit <- 1 - sum((pred - profile)^2) / sum((profile - mean(profile))^2)
  }
  c(e = e, x = x, y = y, a = a, d = d, fit = fit)
}

# Draw engines (spec section 5.1) -------------------------------------------------

# MVN propagation: psi ~ MVN(psi-hat, V-hat) via the package's single
# draw-root convention (mvn_draws/mvn_root). lavaan's vcov of a model with
# linear equality constraints (the fixed-angle direction constraints) is
# singular along the constraints, so the draws satisfy them exactly.
# Consumes the global RNG stream (spec section 5.4).
sem_draws_mvn <- function(fit, boots) {
  psi <- lavaan::coef(fit)
  mvn_draws(boots, as.numeric(psi), as.matrix(lavaan::vcov(fit)))
}

# lavaan bootstrap: a full refit per resample; each replicate's free-parameter
# vector goes through the same map. The seed handed to lavaan is drawn from
# the global stream, so the entry point keeps the package's RNG contract
# (set.seed() immediately before the call reproduces results) regardless of
# lavaan's internal parallel RNG machinery (iseed drives L'Ecuyer streams, so
# results are also reproducible under parallel = "multicore"/"snow").
sem_draws_boot <- function(fit, boots, parallel = "no", ncpus = 1) {
  iseed <- sample.int(.Machine$integer.max, 1)
  reps <- lavaan::bootstrapLavaan(
    fit,
    R = boots, FUN = "coef", iseed = iseed,
    parallel = parallel, ncpus = ncpus
  )
  # Failed/nonconverged replicates: current lavaan keeps all R rows and fills
  # failures with NA (indices also in attr(reps, "error.idx")); older versions
  # removed the rows instead. Handle both by keeping complete rows only -- an
  # NA parameter row must never reach the estimand map.
  keep <- stats::complete.cases(reps)
  n_fail <- (boots - nrow(reps)) + sum(!keep)
  reps <- reps[keep, , drop = FALSE]
  if (nrow(reps) == 0) {
    stop(
      "Every bootstrap replicate failed to converge; no intervals can be ",
      "constructed. The measurement model is likely too unstable at this ",
      "sample size.",
      call. = FALSE
    )
  }
  if (n_fail > 0) {
    warning(
      n_fail, " of ", boots, " bootstrap replicates failed to converge and ",
      "were dropped before interval assembly; the intervals are conditional ",
      "on convergence.",
      call. = FALSE
    )
  }
  reps
}

# Estimation core (spec sections 4.5, 5) -------------------------------------------

# Shared by ssm_sem() and ssm_sem_parameters(): point profile + guards, draws,
# engine-side admissibility filter, transform, and interval assembly through
# ssm_replicate_intervals() verbatim.
sem_estimate <- function(fit, scales, angles_deg, measures, ci_method, boots,
                         interval, contrast, parallel = "no", ncpus = 1) {
  # Multi-group fits are refused outright: the parameter table has one row
  # per (parameter, group), the shared labels impose unintended cross-group
  # equality constraints, and silently indexing group 1 would report a
  # profile that corresponds to no estimand. The invariance-gated multi-group
  # workflow is a separate feature (M5 T4).
  if (lavaan::lavInspect(fit, "ngroups") > 1) {
    stop(
      "Multi-group lavaan fits are not supported yet: the invariance-gated ",
      "multi-group latent SSM workflow is a separate, in-development ",
      "feature. Fit and analyze one group at a time, or use ssm_analyze() ",
      "for observed-score group comparisons.",
      call. = FALSE
    )
  }

  struct <- sem_structure(fit, scales, measures)
  th <- as.numeric(as_radian(as_degree(angles_deg)))
  p <- length(scales)
  m <- length(measures)
  # Single provenance for the projection weights: derived here from the
  # supplied scales/angles for both entry points, so the two can never
  # silently estimate with different projections for the same fit.
  weights <- sem_ols_weights(th, names = scales)

  # The supplied angles must be the angles the model was generated with: the
  # plane loadings lie on the ray at theta_i (up to the harmless reflection),
  # so a mismatch is detectable from the fitted direction. Without this, a
  # forgotten `angles =` silently projects the profile onto the wrong basis.
  lx <- struct$lambda$val[, 2]
  ly <- struct$lambda$val[, 3]
  checkable <- sqrt(lx^2 + ly^2) > 1e-8
  dir_fit <- atan2(ly, lx) %% pi
  dir_th <- th %% pi
  gap <- pmin(
    abs(dir_fit - dir_th), abs(dir_fit - dir_th - pi),
    abs(dir_fit - dir_th + pi)
  )
  off <- which(checkable & gap > 1e-3)
  if (length(off) > 0) {
    stop(
      "The supplied `angles` do not match the fixed angles in the lavaan ",
      "fit (first mismatch: scale `", scales[[off[[1]]]], "`, fitted ",
      "direction ", round(dir_fit[[off[[1]]]] * 180 / pi, 2), " vs supplied ",
      round(dir_th[[off[[1]]]] * 180 / pi, 2), " degrees, modulo 180). Pass ",
      "the angles the model was generated with.",
      call. = FALSE
    )
  }

  # Point profile and the section 4.5 point guard: a disattenuated correlation
  # at or beyond 1 signals misspecification, not a profile to summarize.
  psi_hat <- matrix(as.numeric(lavaan::coef(fit)), nrow = 1)
  point <- sem_profiles(psi_hat, struct)
  rho0 <- do.call(rbind, lapply(point$rho, as.numeric)) # m x p
  # The variance conditions are checked directly (not just through NaN in
  # rho0): with BOTH variances negative their product is positive and rho0
  # comes out finite but sign-corrupted (the double-Heywood case).
  if (any(!is.finite(rho0)) || any(point$var_t <= 0) || any(point$v_m <= 0)) {
    stop(
      "The fitted measurement model implies an undefined latent profile ",
      "(nonpositive common-part or measure variance); the model is not ",
      "admissible for latent SSM estimation.",
      call. = FALSE
    )
  }
  over <- which(abs(rho0) >= 1 - 1e-12, arr.ind = TRUE)
  if (nrow(over) > 0) {
    stop(
      "The model-implied disattenuated correlation reaches |1| for measure `",
      measures[[over[1, 1]]], "` with scale `", scales[[over[1, 2]]],
      "`; disattenuated correlations at or beyond 1 indicate ",
      "misspecification of the measurement model, not a profile to ",
      "summarize.",
      call. = FALSE
    )
  }

  # Parameter draws (both engines yield rows of the free-parameter vector)
  draws <- switch(ci_method,
    mvn = sem_draws_mvn(fit, boots),
    boot = sem_draws_boot(fit, boots, parallel = parallel, ncpus = ncpus)
  )
  n_draws <- nrow(draws)
  prof <- sem_profiles(draws, struct)

  # Engine-side admissibility filter (spec section 4.5): a draw is dropped
  # WHOLE when its parameter row is inadmissible -- never routed through
  # ssm_replicate_intervals()'s degenerate-replicate warning, whose wording is
  # cause-specific to flat/zero-amplitude profiles. Admissible draws with a
  # degenerate profile still flow through and get that existing contract.
  # Every comparison is written non-finite-safe: this filter is the safety
  # net, so it must classify (not crash on) any pathological row that slips
  # past the engines.
  bad_vt <- rowSums(!is.finite(prof$var_t) | prof$var_t <= 0) > 0
  bad_vm <- rowSums(!is.finite(prof$v_m) | prof$v_m <= 0) > 0
  bad_rho <- rep(FALSE, n_draws)
  for (k in seq_len(m)) {
    r <- abs(prof$rho[[k]])
    bad_rho <- bad_rho | rowSums(!is.finite(r) | r >= 1) > 0
  }
  bad_rho <- bad_rho & !(bad_vt | bad_vm) # undefined rho is the variance's fault
  bad <- bad_vt | bad_vm | bad_rho
  n_bad <- sum(bad)
  if (n_bad > 0) {
    # Share of the draws actually in hand: under ci_method = "boot" the
    # engine may already have dropped nonconvergent replicates, and diluting
    # the denominator with the requested count would loosen the escalation
    # threshold exactly when the bootstrap is struggling.
    frac <- n_bad / n_draws
    msg <- paste0(
      n_bad, " of ", n_draws, " parameter draws were inadmissible (",
      sum(bad_vt), " with a nonpositive common-part variance, ",
      sum(bad_vm), " with a nonpositive measure variance, ",
      sum(bad_rho), " with a disattenuated correlation at or beyond 1) and ",
      "were dropped whole before interval assembly."
    )
    if (frac > 0.05) {
      stop(
        msg, " More than 5% of draws are inadmissible, so the intervals ",
        "would be unreliable; consider ci_method = \"boot\" or revising the ",
        "measurement model.",
        call. = FALSE
      )
    }
    warning(msg, call. = FALSE)
  }

  # Transform: one replicate row of (e, x, y, a, d, fit) per admissible draw,
  # per measure; then the existing interval machinery, unchanged.
  keep <- which(!bad)
  par_list <- vector("list", m)
  t0_list <- vector("list", m)
  for (k in seq_len(m)) {
    rk <- prof$rho[[k]][keep, , drop = FALSE]
    par_list[[k]] <- t(apply(rk, 1, sem_ssm_transform, weights = weights,
                             angles_rad = th))
    t0_list[[k]] <- sem_ssm_transform(rho0[k, ], weights, th)
  }
  t <- do.call(cbind, par_list)
  t0 <- unlist(t0_list, use.names = FALSE)
  if (contrast) {
    # Second minus first (displacement via angular distance), sharing
    # param_diff() so the contrast convention has one definition.
    t <- cbind(t, param_diff(par_list[[2]], par_list[[1]]))
    t0 <- c(t0, param_diff(t0_list[[2]], t0_list[[1]]))
  }

  results <- ssm_replicate_intervals(
    t0 = t0,
    t = t,
    interval = interval,
    contrast = contrast,
    replicate_label = if (ci_method == "mvn") "MVN draws" else
      "bootstrap replicates"
  )

  list(results = results, rho0 = rho0, tier = struct$tier, weights = weights)
}

# Shared details constructor for the two entry points, so the fields the
# subclass print/summary methods read can never drift between them.
sem_details <- function(boots, interval, missing, angles_deg, contrast,
                        ci_method) {
  list(
    boots = boots,
    interval = interval,
    listwise = missing == "listwise",
    missing = missing,
    angles = as_degree(angles_deg),
    contrast = contrast,
    score_type = "Latent",
    method = ci_method
  )
}

# Assemble the labeled results/scores data frames (single group, one row per
# measure plus an optional contrast row), mirroring ssm_analyze_corrs().
sem_assemble <- function(est, scales, measures, contrast) {
  m <- length(measures)
  Group <- rep("All", m)
  Measure <- measures
  scores <- as.data.frame(est$rho0)
  colnames(scores) <- scales
  if (contrast) {
    Group <- c(Group, "All")
    Measure <- c(Measure, paste0(measures[[2]], " - ", measures[[1]]))
    scores <- rbind(scores, scores[2, ] - scores[1, ])
  }
  Label <- Measure
  list(
    results = cbind(Label, Group, Measure, est$results),
    scores = cbind(Label, Group, Measure, scores)
  )
}

# Subclass constructor (spec section 7.3) -----------------------------------------

new_ssm_sem <- function(results, scores, details, call, sem, invariance,
                        model) {
  out <- new_ssm(
    results = results,
    scores = scores,
    details = details,
    call = call,
    sem = sem,
    invariance = invariance,
    model = model
  )
  class(out) <- c("circumplex_ssm_sem", class(out))
  out
}

# Exported entry points -----------------------------------------------------------

#' Perform SEM-based (latent-variable) SSM analyses
#'
#' Estimate the Structural Summary Method profile that one or more external
#' measures show against the \emph{latent} circumplex content of a set of
#' scales -- the disattenuated analog of the correlation-based
#' [ssm_analyze()] -- from a structural equation model with the scale angles
#' held fixed at their theoretical values. The measurement model is generated
#' by [ssm_sem_syntax()] and fitted with \pkg{lavaan} on raw covariances;
#' confidence intervals for all SSM parameters are constructed in-package by
#' propagating draws of the model's free parameters through the profile and
#' SSM transforms and applying the same percentile/circular-quantile machinery
#' as [ssm_analyze()]. No lavaan delta-method or percentile interval is ever
#' used for amplitude or displacement (their intervals must respect the
#' angular branch cut, which lavaan's `:=` machinery does not).
#'
#' The latent profile of a measure is its vector of model-implied
#' \emph{disattenuated} correlations with each scale's common (circumplex)
#' content: the scale's error and unique parts are removed from the
#' denominator, and the covariance is restricted to common content in the
#' numerator. All latent quantities are conditional on the fixed-angle
#' measurement model being adequate: global fit is reported by `print()`, and
#' a poorly fitting measurement model makes the latent SSM parameters
#' uninterpretable, not merely imprecise. The fixed angles are theoretical
#' claims, not estimates (use [cpm_fit()] to examine an instrument's real
#' geometry). Latent displacement is the first-harmonic direction of the
#' saturation-modulated disattenuated profile -- heterogeneous scale
#' saturations rotate it exactly as they rotate the observed displacement;
#' the latent layer removes the reliability modulation, nothing more.
#' Model-implied disattenuated correlations at or beyond 1 indicate
#' misspecification and are refused rather than summarized.
#'
#' The point estimates and intervals are reported for elevation, x-value,
#' y-value, amplitude, and displacement (no standard errors are printed
#' anywhere, matching the package's estimate-plus-interval reporting surface).
#' Unlike [ssm_analyze()]'s closed-form estimator, the latent transform is the
#' ordinary-least-squares projection onto the cosine basis, so for unequally
#' spaced angles the two functionals genuinely differ (they coincide exactly
#' for equally spaced angles, and more generally under first- and
#' second-harmonic balance); under OLS the fit value is a bounded R-squared in
#' `[0, 1]` at any spacing.
#'
#' @param data Required. A data frame or matrix containing at least the
#'   circumplex scales and measures.
#' @param scales Required. A character vector of column names, or a numeric
#'   vector of column indexes, from `data` that contains the circumplex scale
#'   scores.
#' @param angles Optional. A numeric vector containing the angular displacement
#'   of each circumplex scale included in `scales`, in degrees
#'   (default = `octants()`). The angles are fixed theoretical constants in the
#'   measurement model, never free parameters.
#' @param measures Required. A character vector (or numeric indexes) of one or
#'   more columns of `data` to be related to the latent circumplex content.
#'   (The single-group latent SSM is the correlation path; latent mean-based
#'   comparisons are a multi-group product and arrive with the invariance
#'   workflow.)
#' @param grouping,invariance Not yet available: the multi-group
#'   invariance-gated latent contrast workflow is under development, and these
#'   arguments currently raise an error if set.
#' @param contrast Optional. A logical indicating whether to output the
#'   difference between exactly two measures' latent SSM parameters (second
#'   minus first, displacement contrast in `(-180, 180]` degrees; default =
#'   FALSE).
#' @param model Optional. The measurement-model tier passed to
#'   [ssm_sem_syntax()]: `"scaled"` (default) or `"strict"`.
#' @param ci_method Optional. How to generate parameter replicates: `"mvn"`
#'   (default) draws from a multivariate normal with lavaan's asymptotic
#'   covariance of the free parameters (fast; one model fit); `"boot"` refits
#'   the model on `boots` bootstrap resamples via
#'   [lavaan::bootstrapLavaan()] (slow; robust to the normal approximation).
#'   Both engines feed the same in-package interval machinery.
#' @param boots Optional. A single positive whole number indicating how many
#'   draws or bootstrap refits to use (default = 2000).
#' @param interval Optional. A single number between 0 and 1 (exclusive)
#'   indicating the confidence level (default = 0.95).
#' @param estimator Optional. The lavaan estimator (default = "MLR": maximum
#'   likelihood with robust "Huber-White" standard errors and a scaled test
#'   statistic, the standard choice for the skewed distributions typical of
#'   circumplex scale scores). The parameter estimates are identical to
#'   `"ML"`; what changes is the covariance the `"mvn"` engine propagates
#'   (already robust via `se`) and the test statistic behind the global fit
#'   indices that `print()` reports (robust/scaled versions are used when
#'   available).
#' @param se Optional. The lavaan standard-error method for the fitted model
#'   (default = "robust.huber.white", the sandwich estimator). This does not
#'   affect the parameter estimates, only the covariance the `"mvn"` engine
#'   propagates: the fixed-angle measurement model is an approximation for
#'   real data, and the package's coverage validation found that
#'   sandwich-based draws keep the intervals calibrated for the
#'   model-conditional estimand under that misspecification where the plain
#'   ML covariance undercovers (displacement ~0.88 instead of 0.95, not
#'   improving with n). Set `se = "standard"` for the classical ML
#'   covariance.
#' @param missing Optional. Either `"listwise"` (default; complete cases) or
#'   `"fiml"` (full-information maximum likelihood via lavaan's
#'   `missing = "ml"`).
#' @param parallel,ncpus Optional. Passed to [lavaan::bootstrapLavaan()] when
#'   `ci_method = "boot"` (defaults `"no"` and 1): the bootstrap refits are
#'   independent and can be distributed across cores. Results for a given
#'   `set.seed()` are reproducible regardless of these settings (the seed
#'   lavaan receives drives its own parallel-safe RNG streams). Ignored by
#'   the `"mvn"` engine.
#' @param ... Optional. Additional arguments passed to [lavaan::cfa()] (e.g.,
#'   `bounds` or estimator-control settings).
#' @return A `circumplex_ssm_sem` object (a subclass of `circumplex_ssm`, so
#'   [ssm_table()] and the `ssm_plot_*` functions work on it), containing
#'   `results` (estimates and intervals), `scores` (the latent profile
#'   vectors), `details`, `call`, plus `sem` (the fitted lavaan model),
#'   `invariance` (reserved; `NULL`), and `model` (tier, generated syntax, and
#'   the OLS projection weights).
#'
#'   Inadmissible parameter draws (a nonpositive common-part or measure
#'   variance, or a disattenuated correlation at or beyond 1) are dropped
#'   whole with a warning naming the causes; if more than 5% of draws are
#'   inadmissible the analysis stops with advice to use `ci_method = "boot"`
#'   or revise the model. Degenerate profiles (flat or zero-amplitude) keep
#'   the same per-parameter `NA` contract as [ssm_analyze()].
#' @section Reproducibility:
#'   This function consumes R's random number stream for both `ci_method`
#'   settings (`"mvn"` through the package's own draws; `"boot"` through a
#'   seed handed to lavaan's bootstrap). Call `set.seed()` immediately before
#'   `ssm_sem()` for reproducible confidence intervals.
#' @family ssm functions
#' @family analysis functions
#' @seealso [ssm_analyze()] for the observed-score SSM, [ssm_sem_syntax()] for
#'   the generated measurement model, and [ssm_sem_parameters()] to reuse a
#'   lavaan fit you have modified or fitted yourself.
#' @export
#' @examplesIf requireNamespace("lavaan", quietly = TRUE)
#' \donttest{
#' data("jz2017")
#' set.seed(12345)
#' res <- ssm_sem(
#'   jz2017,
#'   scales = c("PA", "BC", "DE", "FG", "HI", "JK", "LM", "NO"),
#'   measures = "NARPD",
#'   boots = 500
#' )
#' res
#' summary(res)
#' }
ssm_sem <- function(data, scales, angles = octants(), measures = NULL,
                    grouping = NULL, contrast = FALSE,
                    model = c("scaled", "strict"), invariance = NULL,
                    ci_method = c("mvn", "boot"), boots = 2000,
                    interval = 0.95, estimator = "MLR",
                    se = "robust.huber.white",
                    missing = c("listwise", "fiml"),
                    parallel = "no", ncpus = 1, ...) {
  call <- match.call()
  require_lavaan()

  model <- match.arg(model)
  ci_method <- match.arg(ci_method)
  missing <- match.arg(missing)
  stopifnot(is_char(se, n = 1))
  parallel <- match.arg(parallel, c("no", "multicore", "snow"))
  stopifnot(is.numeric(ncpus) && ncpus >= 1 && ceiling(ncpus) == floor(ncpus))
  stopifnot(is.data.frame(data) || is.matrix(data))
  stopifnot(is_var(scales))
  stopifnot(is.numeric(angles))
  stopifnot(length(scales) == length(angles))
  stopifnot(is_null_or_var(measures))
  stopifnot(is_flag(contrast))
  stopifnot(is.numeric(boots) && boots > 0 && ceiling(boots) == floor(boots))
  stopifnot(is.numeric(interval) && interval > 0 && interval < 1)
  stopifnot(is_char(estimator, n = 1))
  if (!is.null(grouping) || !is.null(invariance)) {
    stop(
      "Multi-group latent SSM (grouping/invariance) is not available yet: ",
      "the invariance-gated latent contrast workflow is a separate, ",
      "in-development feature (M5 T4). Use ssm_analyze() for observed-score ",
      "group comparisons.",
      call. = FALSE
    )
  }
  if (is.null(measures)) {
    stop(
      "`measures` is required: the single-group latent SSM is the ",
      "correlation path. (A single-group latent mean profile is not a ",
      "product: factor means are not identified in one group.)",
      call. = FALSE
    )
  }
  if (contrast && length(measures) != 2) {
    stop("Contrast requires exactly two measures (second minus first).",
      call. = FALSE
    )
  }

  if (is.matrix(data)) data <- as.data.frame(data)
  scales_data <- data[scales]
  scales_names <- colnames(scales_data)
  measures_data <- data[measures]
  measures_names <- colnames(measures_data)
  dat <- cbind(scales_data, measures_data)
  if (missing == "listwise") dat <- stats::na.omit(dat)

  syn <- ssm_sem_syntax(
    scales = scales_names, angles = as.numeric(angles),
    measures = measures_names, model = model
  )
  fit <- lavaan::cfa(
    syn,
    data = dat, estimator = estimator, se = se,
    missing = if (missing == "fiml") "ml" else "listwise", ...
  )

  # Global model health before any SSM output (spec section 4.5)
  if (!lavaan::lavInspect(fit, "converged")) {
    stop(
      "The measurement model did not converge; no latent SSM parameters ",
      "can be reported. Consider model = \"strict\", a different estimator, ",
      "or examining the instrument's geometry with cpm_fit().",
      call. = FALSE
    )
  }
  post_ok <- tryCatch(
    suppressWarnings(lavaan::lavInspect(fit, "post.check")),
    error = function(e) TRUE
  )
  if (!isTRUE(post_ok)) {
    warning(
      "lavaan's post-estimation checks flagged the fitted measurement model ",
      "(e.g., a negative variance estimate); interpret the latent SSM ",
      "parameters with caution and inspect the fit stored in `$sem`.",
      call. = FALSE
    )
  }

  est <- sem_estimate(
    fit,
    scales = scales_names, angles_deg = as.numeric(angles),
    measures = measures_names, ci_method = ci_method, boots = boots,
    interval = interval, contrast = contrast, parallel = parallel,
    ncpus = ncpus
  )
  parts <- sem_assemble(est, scales_names, measures_names, contrast)

  new_ssm_sem(
    results = parts$results,
    scores = parts$scores,
    details = sem_details(
      boots, interval, missing, as.numeric(angles), contrast, ci_method
    ),
    call = call,
    sem = fit,
    invariance = NULL,
    model = list(tier = model, syntax = syn, weights = est$weights)
  )
}

#' Calculate latent SSM parameters from a fitted lavaan measurement model
#'
#' The low-level adapter behind [ssm_sem()]: take an already fitted
#' \pkg{lavaan} model of a fixed-angle circumplex measurement structure (as
#' generated by [ssm_sem_syntax()], possibly user-modified -- e.g., a
#' partial-invariance respecification) and compute latent SSM parameter
#' estimates with in-package confidence intervals. Compatibility with the
#' expected parameter structure is checked structurally (the named loading,
#' factor-covariance, and measure-covariance parameters must be present), not
#' by provenance.
#'
#' @param fit Required. A fitted lavaan object whose model preserves the
#'   [ssm_sem_syntax()] parameter structure (factors `g`, `cx`, `cy`; the
#'   measures covarying with them). For `ci_method = "mvn"`, fit the model
#'   with robust (sandwich) standard errors (lavaan's
#'   `se = "robust.huber.white"`, [ssm_sem()]'s default) so the propagated
#'   covariance stays valid when the fixed-angle model is an approximation;
#'   see the `se` argument of [ssm_sem()].
#' @param scales Required. A character vector with the scale (indicator)
#'   names, in the same order as `angles`.
#' @param angles Optional. A numeric vector of the scales' theoretical angles
#'   in degrees (default = `octants()`). Must be the angles the model was
#'   generated with.
#' @param measures Required. A character vector of the measure names.
#' @param ci_method,boots,interval,contrast,parallel,ncpus See [ssm_sem()].
#' @return A `circumplex_ssm_sem` object; see [ssm_sem()].
#' @inheritSection ssm_sem Reproducibility
#' @family ssm functions
#' @family analysis functions
#' @export
#' @examplesIf requireNamespace("lavaan", quietly = TRUE)
#' \donttest{
#' data("jz2017")
#' scales <- c("PA", "BC", "DE", "FG", "HI", "JK", "LM", "NO")
#' syn <- ssm_sem_syntax(scales = scales, angles = octants(), measures = "NARPD")
#' # Robust (sandwich) SEs so the mvn engine propagates a
#' # misspecification-consistent covariance (ssm_sem()'s default)
#' fit <- lavaan::cfa(syn, data = jz2017, se = "robust.huber.white")
#' set.seed(12345)
#' ssm_sem_parameters(fit, scales = scales, measures = "NARPD", boots = 500)
#' }
ssm_sem_parameters <- function(fit, scales, angles = octants(), measures,
                               ci_method = c("mvn", "boot"), boots = 2000,
                               interval = 0.95, contrast = FALSE,
                               parallel = "no", ncpus = 1) {
  call <- match.call()
  require_lavaan()
  ci_method <- match.arg(ci_method)
  stopifnot(inherits(fit, "lavaan"))
  stopifnot(is_char(scales))
  stopifnot(is.numeric(angles))
  stopifnot(length(scales) == length(angles))
  stopifnot(is_char(measures))
  stopifnot(is.numeric(boots) && boots > 0 && ceiling(boots) == floor(boots))
  stopifnot(is.numeric(interval) && interval > 0 && interval < 1)
  stopifnot(is_flag(contrast))
  if (contrast && length(measures) != 2) {
    stop("Contrast requires exactly two measures (second minus first).",
      call. = FALSE
    )
  }
  if (!lavaan::lavInspect(fit, "converged")) {
    stop("The supplied lavaan fit did not converge; no latent SSM ",
      "parameters can be reported.",
      call. = FALSE
    )
  }
  parallel <- match.arg(parallel, c("no", "multicore", "snow"))
  stopifnot(is.numeric(ncpus) && ncpus >= 1 && ceiling(ncpus) == floor(ncpus))

  est <- sem_estimate(
    fit,
    scales = scales, angles_deg = as.numeric(angles), measures = measures,
    ci_method = ci_method, boots = boots, interval = interval,
    contrast = contrast, parallel = parallel, ncpus = ncpus
  )

  # The mvn engine propagates whatever covariance the fit carries; the
  # package's coverage validation found the plain ML covariance undercovers
  # displacement (about 0.88, not improving with n) when the fixed-angle
  # model is an approximation, so a non-robust fit gets a warning here
  # (after the hard guards, so refusals are not preceded by advice about
  # intervals that will never exist). Only raw-data fits are warned: with
  # summary-moment (sample.cov) input, lavaan cannot compute a sandwich, so
  # the plain covariance is all there is.
  fit_se <- tryCatch(
    lavaan::lavInspect(fit, "options")$se,
    error = function(e) NULL
  )
  has_raw_data <- !inherits(
    tryCatch(lavaan::lavInspect(fit, "data"), error = function(e) e),
    "error"
  )
  if (ci_method == "mvn" && identical(fit_se, "standard") && has_raw_data) {
    warning(
      "This lavaan fit uses se = \"standard\", so the \"mvn\" intervals ",
      "propagate the plain ML covariance, which the package's coverage ",
      "validation found to undercover displacement when the fixed-angle ",
      "model is only an approximation. Refit with ",
      "se = \"robust.huber.white\" (ssm_sem()'s default).",
      call. = FALSE
    )
  }
  parts <- sem_assemble(est, scales, measures, contrast)

  lav_missing <- tryCatch(
    lavaan::lavInspect(fit, "options")$missing,
    error = function(e) "listwise"
  )
  missing <- if (identical(lav_missing, "ml") ||
    identical(lav_missing, "ml.x")) "fiml" else "listwise"

  new_ssm_sem(
    results = parts$results,
    scores = parts$scores,
    details = sem_details(
      boots, interval, missing, as.numeric(angles), contrast, ci_method
    ),
    call = call,
    sem = fit,
    invariance = NULL,
    model = list(tier = est$tier, syntax = NULL, weights = est$weights)
  )
}

# Subclass methods (spec section 7.3) ----------------------------------------------

# Print method for objects of ssm_sem class: prepend the measurement-model
# block (tier, global fit indices -- computed quantities printed without
# verdicts attached), then delegate to the inherited profile printer (which
# carries the amplitude-CI and fit guardrail notes unchanged).
#' @method print circumplex_ssm_sem
#' @export
print.circumplex_ssm_sem <- function(x, digits = 3, ...) {
  cat("\n# Latent (SEM-based) SSM\n\n")
  cat("Measurement model:\t", x$model$tier, "fixed-angle circumplex\n")
  if (has_lavaan()) {
    n <- lavaan::lavInspect(x$sem, "ntotal")
    fm <- lavaan::fitMeasures(x$sem)
    # Prefer the robust/scaled fit statistics when the fit carries them
    # (estimator = "MLR", ssm_sem()'s default): under the skewed
    # distributions typical of circumplex scores, the naive chi-square
    # over-rejects and the indices computed from it are distorted.
    pick <- function(...) {
      for (nm in c(...)) if (nm %in% names(fm)) return(fm[[nm]])
      NA_real_
    }
    robust <- "chisq.scaled" %in% names(fm)
    cat(
      sprintf("Global fit (N = %d%s):", n, if (robust) ", robust" else ""),
      sprintf(
        "chisq(%g) = %s, p = %s",
        pick("df.scaled", "df"),
        format(round(pick("chisq.scaled", "chisq"), digits)),
        format(round(pick("pvalue.scaled", "pvalue"), digits))
      ), "\n"
    )
    cat(sprintf(
      "\t\t\tCFI = %s, RMSEA = %s, SRMR = %s\n",
      format(round(pick("cfi.robust", "cfi.scaled", "cfi"), digits)),
      format(round(pick("rmsea.robust", "rmsea.scaled", "rmsea"), digits)),
      format(round(pick("srmr"), digits))
    ))
  }
  NextMethod()
}

# Summary method for objects of ssm_sem class: owns the inferential-method and
# missing-data lines (the inherited summary would print "Bootstrap Resamples"
# for MVN draws and a Listwise Deletion line -- a false statement of the
# method; spec section 7.3).
#' @method summary circumplex_ssm_sem
#' @export
summary.circumplex_ssm_sem <- function(object, digits = 3, ...) {
  replicate_label <- if (identical(object$details$method, "mvn")) {
    "\nMVN Draws:\t\t"
  } else {
    "\nBootstrap Refits:\t"
  }
  missing_label <- if (identical(object$details$missing, "fiml")) {
    "FIML"
  } else {
    "Listwise deletion"
  }
  cat(
    "\nStatistical Basis:\t", object$details$score_type, "Scores",
    replicate_label, object$details$boots,
    "\nConfidence Level:\t", object$details$interval,
    "\nMissing Data:\t\t", missing_label,
    "\nScale Displacements:\t", as.numeric(object$details$angles),
    "\n\n"
  )
  print(object)
}
